before_script: "npm install --only=dev"
language: node_js
node_js:
    - 4
    - 6
    - 8
    - 9
script:
  - npm run test-coverage
after_success:
  - npm install coveralls@~3.0.0
  - npm run report-coverage
branches:
  only:
    - master
